### ISSUE TITLE
Guest MAC address should not be initialized by hardware

### ISSUE THREAD

**Issue by JayFoxRox** [LukeUsher/Cxbx-Reloaded#15]
This code in `NVNetDevice::Init()` looks odd:

https://github.com/LukeUsher/Cxbx-Reloaded/blob/4997336d93b42c94e67e387efbd75e0f99b4bd60/src/devices/EmuNVNet.cpp#L540-L546

To my knowledge, the hardware does not have its own MAC address.
The MAC address is only assigned by the network driver, not on device init.

This is also why #13 is required: the MAC will be read from EEPROM and written at runtime, the MAC address that's hardcoded in the code remains unused.

I'm not sure which value the MAC register has on a cold-boot.
This should be looked into.

As this problem also exists in XQEMU, please send an upstream PR, too.

**Comment by LukeUsher** [comment]
PR submitted to XQEMU https://github.com/xqemu/xqemu/pull/218
