### ISSUE TITLE
XQEMU should be credited in README for NVNet

### ISSUE THREAD

**Issue by JayFoxRox** [LukeUsher/Cxbx-Reloaded#16]
README only credits XQEMU for NV2A, but the NVNet also comes from XQEMU. This isn't legal requirement, but it would make sense to mention it (as the original statement is more and more false).

*Strictly speaking this is also true for some of the USB LLE; but I didn't check to what extend.*

**Comment by LukeUsher** [comment]
Updated readme to include NVNet in the list
