### ISSUE TITLE
Xbox dashboard 3944 no longer seems to work

### ISSUE THREAD

**Issue by Voxel-Studios** [LukeUsher/Cxbx-Reloaded#17]
Hello, and I apologize in advance if this is not a suitable place to ask for help, however I feel that it should be made aware just in case.

I recently got the old 3944 dashboard files to try and emulate through Cxbx, however the latest builds seem to just give me constant breakpoint errors, and the emulator ends up crashing every single time.
I have observed the _compatability list_, and saw that this version of the dash should indeed work, but it seems that it does not.

I have attempted to build the source from the point where 3944 dash was fully implemented and working (Nov 2011), but even then I'm encountering horrible building errors in Visual Studio 2008 and am struggling to fix them. (I can compile the latest builds just fine in VS 2015, but again those builds cannot seem to emulate the 3944 dash on my side)

If you need to know what I'm running on, I am using Windows 10 (x64). Any aid to try and get the dash up and runnning is much appreciated.

**Comment by LukeUsher** [comment]
The dashboard can only run if it is installed on the Emulated Hard Drive.
The files need to be copied to "%AppData%\Cxbx-Reloaded\EmuDisk\Partition2" and ran from there.

This is because the dashboard attempts to read files directly from that location.

**Comment by Voxel-Studios** [comment]
You are a life-saver! Everything's working perfectly! Thank you so much. :)
