### ISSUE TITLE
will this emulator be available for android

### ISSUE THREAD

**Issue by Jordanesquivez** [LukeUsher/Cxbx-Reloaded#19]

**Comment by LukeUsher** [comment]
It is impossible for this to happen for two reasons:

1. Cxbx doesn't really emulate the Xbox processor, the whole approach to emulation relies on the fact that PC's and Xbox share a common architecture. The xbox code runs directly on the host processor without any translation steps.

2. The Kernel HLE emulation strongly relies on the Windows NT API which is unavailable on all operating systems other than Windows. A port of Wine could solve this, but we are having trouble getting it to run under Wine on Linux already, Android would be even more difficult.

I'm sorry, but this is just not possible

**Comment by Jordanesquivez** [comment]
Oh I see... so it's impossible... the thing I remembered in 2014 when I thouht that emulating the ps2 on android was impossible ... but it was possible have you heard abt it "Play!"?? perhaps it's possible to emulate xbox on android but through hard work .. anyways I'm really interested in your project, I think cxbx is really awesome and maybe I can help... I'm very good with gpu... let me know what u think??

**Comment by CloudyHeart** [comment]
Emulating the Xbox on Android is possible, but porting Cxbx-Reloaded to (non-x86) Android is not. Porting XQEMU to Android would be possible, to my understanding, but it's not likely to happen for a long time.
