### ISSUE TITLE
Resolving incorrect paths

### ISSUE THREAD

**Issue by x1nixmzeng** [LukeUsher/Cxbx-Reloaded#2]
Tested on your latest commit de0c650d8d52c3ce4f1bb36c9e29c77324af7f98

```
EmuKrnl (0x159C): RtlInitAnsiString
(
   DestinationString   : 0x0493FC48
   SourceString        : 0x0493FC84 ("t:\media\cour.xft")
);
EmuKrnl (0x159C): NtCreateFile
(
   FileHandle          : 0x0493FC50
   DesiredAccess       : 0x80100080
   ObjectAttributes    : 0x0493FC34 ("t:\media\cour.xft")
   IoStatusBlock       : 0x0493FC40
   AllocationSize      : 0x00000000
   FileAttributes      : 0x00000080
   ShareAccess         : 0x00000001
   CreateDisposition   : 0x00000001
   CreateOptions       : 0x00000060
);
EmuKrnl : NtCreateFile Corrected path..
.  Org:"t:\media\cour.xft"
  New:"$CxbxPath\EmuDiskPartition1\TDATA\5842000cmedia\cour.xft"
EmuKrnl (0x159C): NtCreateFile Failed! (0xC000003A)
EmuKrnl (0x159C): RtlNtStatusToDosError
(
   Status              : 0xC000003A
);
EmuMain (0x159C): Recieved Breakpoint Exception (int 3)
```

The path resolved for reading local media is incorrect - where the requested file is a symbolic link to the `t:\` drive, added like this:

```
EmuKrnl (0x159C): IoCreateSymbolicLink
(
   SymbolicLinkName    : 0x00037AF8 (\??\U:)
   DeviceName          : 0x0493FDE4 (\Device\Harddisk0\partition1\UDATA\5842000c
)
);
```

I've uploaded the XBE files + media causing this issue: http://www.speedyshare.com/Xa9dY/xbe-controller-test.7z

Note - this has also initialised D3D by this point.

**Comment by LukeUsher** [comment]
The current symbolic link code is a very rushed port from Dxbx, I probably messed something up while translating the code from Delphi.

I'll look into it

**Comment by x1nixmzeng** [comment]
Wierdly, the file this XBE is trying to resolve doesn't exist. I'm not sure it is the best test case.

**Comment by LukeUsher** [comment]
ControllerTest0.xbe runs fine after pressing 'ignore' on the breakpoints that occur, not sure why they're happening yet but it seems to be unrelated to file paths.
