### ISSUE TITLE
CxbxCreateSymbolicLink creates incorrect links to the utility drive

### ISSUE THREAD

**Issue by StrikerX3** [LukeUsher/Cxbx-Reloaded#24]
Whenever a game calls IoCreateSymbolicLink directly with a path to the utility drive (using Z:\ or \Device\Harddisk0\Partition6), Cxbx is not properly relocating the actual path to the Cxbx_ZDATA_<title ID> subfolder. These links are instead created at the root of the utility drive folder, at %APPDATA%\Cxbx-Reloaded\EmuDisk\Partition6. Some titles attempt to rename, delete or otherwise access these files after copying them, but not before recreating the symbolic link, which means they can no longer find the files since the link now points to a different folder.

**Comment by LukeUsher** [comment]
The ZDATA_ folders are not created on the Xbox and should probably be removed, this would prevent having to hack CxbxCreateSymbolicLink to work around this.

It would be good if we could remove our patches to XMountUtilityDrive and let the titles themselves take care of this, but HDD emulation isn't quite there yet, we need to emulate low-level HDD partition tables first.

**Comment by LukeUsher** [comment]
Closing as I have removed the generation of ZDATA_ folders.
