### ISSUE TITLE
* IDirect3D8::CreateDevice failed (Invaild Call)

### ISSUE THREAD

**Issue by fuhuan416** [LukeUsher/Cxbx-Reloaded#6]
When i start the game [IronPhoenix], a few seconds i get a message:
CxbxKrnl
EmuMain (0x1218): Recieved Fatal Message:
* IDirect3D8::CreateDevice failed (Invaild Call)

There're xbe info and Debug console infoes below:
`XBE information generated by CXBX (Version 0.8.1-Pre3)

Title identified as "Iron Phoenix"

Dumping XBE file header...

Magic Number                     : XBEH
Digitial Signature               : <Hex Dump>
                                   A44791757C2E9EBA1066A17D0E5A2716
                                   7D22A3CA83891BBB1A4AA88FBFA4EA85
                                   D9BF986C149E1978A53E00C7C3ADD490
                                   9F38CC10BE59BD96A863CF1ECC28EB03
                                   158F52FF5B88A76F274622CB1FCEEC6F
                                   E01D58E368F2BA1D0D899AC951B41888
                                   7BB9A6483F16D344C4F8B5A36D43170D
                                   097AE13986BE3E0736D38838A3C76F8C
                                   3A5A4AC8595182D3D03139E4517CAA54
                                   0096F8BFE41790114B26404BE7F4002D
                                   BB1B001B40C94AED2DF6D3FB21211848
                                   97E7A8AD8B09A0C73E0A93AAACE6E03C
                                   000135A1DE53DEB91BDFDF1F1FDEC169
                                   3327DCE420CF1116FBB8FB5713A83FEE
                                   6788D2833125D77A6DF72DF01EEBAF2D
                                   EB807C4DE74FB91909FB2924FB859D22
                                   </Hex Dump>
Base Address                     : 0x00010000
Size of Headers                  : 0x00000BE4
Size of Image                    : 0x0049DDE0
Size of Image Header             : 0x00000184
TimeDate Stamp                   : 0x41E20D53 (Mon Jan 10 13:06:27 2005)
Certificate Address              : 0x00010184
Number of Sections               : 0x00000012
Section Headers Address          : 0x00010370
Init Flags                       : 0x00000001 [Mount Utility Drive] [Format Utility Drive] [Setup Harddisk] 
Entry Point                      : 0xA8ECA08E (Retail: 0x0010F725, Debug: 0x3C693DC5)
TLS Address                      : 0x00315D84
(PE) Stack Commit                : 0x00010000
(PE) Heap Reserve                : 0x00100000
(PE) Heap Commit                 : 0x00001000
(PE) Base Address                : 0x00010AE0
(PE) Size of Image               : 0x004BC3E0
(PE) Checksum                    : 0x004C679C
(PE) TimeDate Stamp              : 0x41E20D37 (Mon Jan 10 13:05:59 2005)
Debug Pathname Address           : 0x000108FC ("d:\Projects\XBlade\Game\XBox\Release\default.exe")
Debug Filename Address           : 0x00010921 ("default.exe")
Debug Unicode filename Address   : 0x000108E4 (L"default.exe")
Kernel Image Thunk Address       : 0x5B5DF9B6 (Retail: 0x0030B900, Debug: 0xB4EC08E4)
NonKernel Import Dir Address     : 0x00000000
Library Versions                 : 0x0000000E
Library Versions Address         : 0x000107F4
Kernel Library Version Address   : 0x00010844
XAPI Library Version Address     : 0x000107F4
Logo Bitmap Address              : 0x00010930
Logo Bitmap Size                 : 0x000002B2

Dumping XBE Certificate...

Size of Certificate              : 0x000001EC
TimeDate Stamp                   : 0x41ED7974 (Wed Jan 19 05:02:44 2005)
Title ID                         : 0x53410003
Title                            : L"Iron Phoenix"
Alternate Titles IDs             : 0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
                                   0x00000000
Allowed Media                    : 0x00000202
Game Region                      : 0x00000007
Game Ratings                     : 0x00000003
Disk Number                      : 0x00000000
Version                          : 0x00000001
LAN Key                          : 951253A6530C012A6685D8E615B2574C
Signature Key                    : 33E89B90CC10E00FC97997B009E7548C
Title Alternate Signature Keys : <Hex Dump>
                                   E2D8BD1E45C3531E6C2D2F60D5A27EF9
                                   2198E3185D00E3F4C96DE71364FB9C41
                                   DB9E471214BFA507B3AEE39179FF6526
                                   9284727FE21B34EBDAF6125C4715A4A9
                                   7C02A49EF3AC61ED98DAA28EDBDC597A
                                   5748BA16F530DC994350562BDDD1EEE9
                                   AD9180833918ABA4AF92CF2A88B73009
                                   3E11786BA88AE58AA2DA46CBAF8AA2DE
                                   0DF8A36EAF9085DB5FAE936411331C5A
                                   67BAE5FD96B046ADDF117CD2FBEA7258
                                   D042FCF127ACBAF81C531730252CE192
                                   D3C10E6F3267F065ADB991CE5392136C
                                   C734F44A9DED5458306A0DF49FE420B9
                                   D9A03A600A0D357F3DEC02A2C1682DD0
                                   C950745A938CF830126BA9F795220C85
                                   023F0D538B7233E3EA91CD2CCFCAF5FD
                                   </Hex Dump>

Dumping XBE Section Headers...

Section Name                     : 0x00010782 (".text")
Flags                            : 0x00000000 (Preload) (Executable) (Head Page RO) 
Virtual Address                  : 0x00011000
Virtual Size                     : 0x00215ECC
Raw Address                      : 0x00001000
Size of Raw                      : 0x00215ECC
Section Name Address             : 0x00010782
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010760
Tail Shared Reference Count Addr : 0x00010762
Section Digest                   : 21AD9F3C47EC159606D7108871795B434DC94F70

Section Name                     : 0x00010788 ("D3D")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x00226EE0
Virtual Size                     : 0x00014CE0
Raw Address                      : 0x00217000
Size of Raw                      : 0x000111F8
Section Name Address             : 0x00010788
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010762
Tail Shared Reference Count Addr : 0x00010764
Section Digest                   : B893EDC28C037574A21D58DF8F02F799110E63FB

Section Name                     : 0x0001078C ("D3DX")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x0023BBC0
Virtual Size                     : 0x00000868
Raw Address                      : 0x00229000
Size of Raw                      : 0x00000868
Section Name Address             : 0x0001078C
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010764
Tail Shared Reference Count Addr : 0x00010766
Section Digest                   : B15C957584C14245A2BB298A547604DB385808D2

Section Name                     : 0x00010791 ("XGRPH")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x0023C440
Virtual Size                     : 0x00020488
Raw Address                      : 0x0022A000
Size of Raw                      : 0x0001F80C
Section Name Address             : 0x00010791
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010766
Tail Shared Reference Count Addr : 0x00010768
Section Digest                   : 7EF2F74BCE1EA7C14503469EB76A0CB17895755A

Section Name                     : 0x00010797 ("DSOUND")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x0025C8E0
Virtual Size                     : 0x0001E86C
Raw Address                      : 0x0024A000
Size of Raw                      : 0x0001E604
Section Name Address             : 0x00010797
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010768
Tail Shared Reference Count Addr : 0x0001076A
Section Digest                   : 80F377042B5ABE2FF73594CBAB8F2E2BBA91D9C1

Section Name                     : 0x0001079E ("WMADEC")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x0027B160
Virtual Size                     : 0x0001907C
Raw Address                      : 0x00269000
Size of Raw                      : 0x0001907C
Section Name Address             : 0x0001079E
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001076A
Tail Shared Reference Count Addr : 0x0001076C
Section Digest                   : 24D7DEE3C34D806B89E0EF1F0865F73C50AD52BB

Section Name                     : 0x000107A5 ("XMV")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x002941E0
Virtual Size                     : 0x00027FEC
Raw Address                      : 0x00283000
Size of Raw                      : 0x00027FDC
Section Name Address             : 0x000107A5
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001076C
Tail Shared Reference Count Addr : 0x0001076E
Section Digest                   : 47B0840CCD6DD98CEC14499C0CC01DA81DA1BB87

Section Name                     : 0x000107A9 ("XACTENG")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x002BC1E0
Virtual Size                     : 0x0000B9D8
Raw Address                      : 0x002AB000
Size of Raw                      : 0x0000B984
Section Name Address             : 0x000107A9
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001076E
Tail Shared Reference Count Addr : 0x00010770
Section Digest                   : B50D35394E2F9B5DC3BB82C42DF326C899ED87E6

Section Name                     : 0x000107B1 ("XNET")
Flags                            : 0x00000000 (Preload) (Executable) (Tail Page RO) 
Virtual Address                  : 0x002C7BC0
Virtual Size                     : 0x00012F20
Raw Address                      : 0x002B7000
Size of Raw                      : 0x00012F20
Section Name Address             : 0x000107B1
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010770
Tail Shared Reference Count Addr : 0x00010772
Section Digest                   : CC9FF3EE46E3EEB47238CF4102CC4E18D9E801B9

Section Name                     : 0x000107B6 ("XONLINE")
Flags                            : 0x00000000 (Preload) (Executable) (Head Page RO) 
Virtual Address                  : 0x002DAAE0
Virtual Size                     : 0x00027F84
Raw Address                      : 0x002CA000
Size of Raw                      : 0x00027F84
Section Name Address             : 0x000107B6
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010772
Tail Shared Reference Count Addr : 0x00010774
Section Digest                   : 0F43DC2D8693F0B16200EB94516F7E945EB43063

Section Name                     : 0x000107BE ("XPP")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x00302A80
Virtual Size                     : 0x00008E80
Raw Address                      : 0x002F2000
Size of Raw                      : 0x00008E80
Section Name Address             : 0x000107BE
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010774
Tail Shared Reference Count Addr : 0x00010776
Section Digest                   : E2CECC89DC4E5984502D2DE01B8A6B5420C1D25D

Section Name                     : 0x000107C2 (".rdata")
Flags                            : 0x00000000 (Preload) (Executable) 
Virtual Address                  : 0x0030B900
Virtual Size                     : 0x00048074
Raw Address                      : 0x002FB000
Size of Raw                      : 0x00048064
Section Name Address             : 0x000107C2
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010776
Tail Shared Reference Count Addr : 0x00010778
Section Digest                   : 62F8C16BEF21DA9F4F6DACCD8DF8D99E832FECC2

Section Name                     : 0x000107C9 (".data")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x00353980
Virtual Size                     : 0x0014E398
Raw Address                      : 0x00344000
Size of Raw                      : 0x0000D568
Section Name Address             : 0x000107C9
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010778
Tail Shared Reference Count Addr : 0x0001077A
Section Digest                   : C305760FF268AB34D04957679D802FEDE6D0EC61

Section Name                     : 0x000107CF ("DOLBY")
Flags                            : 0x00000000 (Preload) (Executable) (Tail Page RO) 
Virtual Address                  : 0x004A1D20
Virtual Size                     : 0x00007180
Raw Address                      : 0x00352000
Size of Raw                      : 0x0000716C
Section Name Address             : 0x000107CF
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001077A
Tail Shared Reference Count Addr : 0x0001077C
Section Digest                   : C8C9142DCCBD31BDCA9A2D94E0ACC47C2048D615

Section Name                     : 0x000107D5 ("XON_RD")
Flags                            : 0x00000000 (Preload) (Executable) (Head Page RO) 
Virtual Address                  : 0x004A8EA0
Virtual Size                     : 0x00001A90
Raw Address                      : 0x0035A000
Size of Raw                      : 0x00001A90
Section Name Address             : 0x000107D5
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001077C
Tail Shared Reference Count Addr : 0x0001077E
Section Digest                   : E791C7550E5A5462ECF66AB27D33377FE850C5BB

Section Name                     : 0x000107DC (".data1")
Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
Virtual Address                  : 0x004AA940
Virtual Size                     : 0x000000E0
Raw Address                      : 0x0035C000
Size of Raw                      : 0x000000B0
Section Name Address             : 0x000107DC
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001077E
Tail Shared Reference Count Addr : 0x0001077E
Section Digest                   : 7F154B1A51860A1447B77E7BA73968FD275EC053

Section Name                     : 0x000107E3 ("$$XTIMAG")
Flags                            : 0x00000000 (Inserted File) (Tail Page RO) 
Virtual Address                  : 0x004AAA20
Virtual Size                     : 0x00002800
Raw Address                      : 0x0035D000
Size of Raw                      : 0x00002800
Section Name Address             : 0x000107E3
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x0001077E
Tail Shared Reference Count Addr : 0x00010780
Section Digest                   : E30887B82C6272FB51615BECE2A1753B141E8985

Section Name                     : 0x000107ED (".XTLID")
Flags                            : 0x00000000 (Inserted File) (Head Page RO) (Tail Page RO) 
Virtual Address                  : 0x004AD220
Virtual Size                     : 0x00000BA8
Raw Address                      : 0x00360000
Size of Raw                      : 0x00000BA8
Section Name Address             : 0x000107ED
Section Reference Count          : 0x00000000
Head Shared Reference Count Addr : 0x00010780
Tail Shared Reference Count Addr : 0x00010780
Section Digest                   : 9B79E25F5DCFA3012DC18D2112B1593E51184FC1

Dumping XBE Library Versions...

Library Name                     : XAPILIB
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : D3D8
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : D3DX8
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : XGRAPHC
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0009, Retail, Approved

Library Name                     : DSOUND
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : XBOXKRNL
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : XMV
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : XACTENG
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0006, Retail, Approved

Library Name                     : XONLINES
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0009, Retail, Possibly Approved

Library Name                     : UIX
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0009, Retail, Approved

Library Name                     : XVOICE
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0004, Retail, Approved

Library Name                     : VOICMAIL
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0804, Retail, Approved

Library Name                     : LIBCMT
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Library Name                     : LIBCPMT
Version                          : 1.0.5849
Flags                            : QFEVersion : 0x0001, Retail, Approved

Dumping XBE TLS...

Data Start Address               : 0x00000000
Data End Address                 : 0x00000000
TLS Index Address                : 0x0037E598
TLS Callback Address             : 0x00000000
Size of Zero Fill                : 0x00000090
Characteristics                  : 0x00000000
`

`WndMain: Debug console allocated.
Xbe::Xbe: Opening Xbe file...OK
Xbe::Xbe: Storing Xbe Path...OK
Xbe::Xbe: Reading Image Header...OK
Xbe::Xbe: Reading Image Header Extra Bytes...OK
Xbe::Xbe: Reading Certificate...OK
Xbe::Xbe: Title identified as Iron Phoenix
Xbe::Xbe: Reading Section Headers...
Xbe::Xbe: Reading Section Header 0x0000...OK
Xbe::Xbe: Reading Section Header 0x0001...OK
Xbe::Xbe: Reading Section Header 0x0002...OK
Xbe::Xbe: Reading Section Header 0x0003...OK
Xbe::Xbe: Reading Section Header 0x0004...OK
Xbe::Xbe: Reading Section Header 0x0005...OK
Xbe::Xbe: Reading Section Header 0x0006...OK
Xbe::Xbe: Reading Section Header 0x0007...OK
Xbe::Xbe: Reading Section Header 0x0008...OK
Xbe::Xbe: Reading Section Header 0x0009...OK
Xbe::Xbe: Reading Section Header 0x000A...OK
Xbe::Xbe: Reading Section Header 0x000B...OK
Xbe::Xbe: Reading Section Header 0x000C...OK
Xbe::Xbe: Reading Section Header 0x000D...OK
Xbe::Xbe: Reading Section Header 0x000E...OK
Xbe::Xbe: Reading Section Header 0x000F...OK
Xbe::Xbe: Reading Section Header 0x0010...OK
Xbe::Xbe: Reading Section Header 0x0011...OK
Xbe::Xbe: Reading Section Names...
Xbe::Xbe: Reading Section Name 0x0000...OK (.text)
Xbe::Xbe: Reading Section Name 0x0001...OK (D3D)
Xbe::Xbe: Reading Section Name 0x0002...OK (D3DX)
Xbe::Xbe: Reading Section Name 0x0003...OK (XGRPH)
Xbe::Xbe: Reading Section Name 0x0004...OK (DSOUND)
Xbe::Xbe: Reading Section Name 0x0005...OK (WMADEC)
Xbe::Xbe: Reading Section Name 0x0006...OK (XMV)
Xbe::Xbe: Reading Section Name 0x0007...OK (XACTENG)
Xbe::Xbe: Reading Section Name 0x0008...OK (XNET)
Xbe::Xbe: Reading Section Name 0x0009...OK (XONLINE)
Xbe::Xbe: Reading Section Name 0x000A...OK (XPP)
Xbe::Xbe: Reading Section Name 0x000B...OK (.rdata)
Xbe::Xbe: Reading Section Name 0x000C...OK (.data)
Xbe::Xbe: Reading Section Name 0x000D...OK (DOLBY)
Xbe::Xbe: Reading Section Name 0x000E...OK (XON_RD)
Xbe::Xbe: Reading Section Name 0x000F...OK (.data1)
Xbe::Xbe: Reading Section Name 0x0010...OK ($$XTIMAG)
Xbe::Xbe: Reading Section Name 0x0011...OK (.XTLID)
Xbe::Xbe: Reading Library Versions...
Xbe::Xbe: Reading Library Version 0x0000...OK
Xbe::Xbe: Reading Library Version 0x0001...OK
Xbe::Xbe: Reading Library Version 0x0002...OK
Xbe::Xbe: Reading Library Version 0x0003...OK
Xbe::Xbe: Reading Library Version 0x0004...OK
Xbe::Xbe: Reading Library Version 0x0005...OK
Xbe::Xbe: Reading Library Version 0x0006...OK
Xbe::Xbe: Reading Library Version 0x0007...OK
Xbe::Xbe: Reading Library Version 0x0008...OK
Xbe::Xbe: Reading Library Version 0x0009...OK
Xbe::Xbe: Reading Library Version 0x000A...OK
Xbe::Xbe: Reading Library Version 0x000B...OK
Xbe::Xbe: Reading Library Version 0x000C...OK
Xbe::Xbe: Reading Library Version 0x000D...OK
Xbe::Xbe: Reading Kernel Library Version...OK
Xbe::Xbe: Reading Xapi Library Version...OK
Xbe::Xbe: Reading Sections...
Xbe::Xbe: Reading Section 0x0000...OK
Xbe::Xbe: Reading Section 0x0001...OK
Xbe::Xbe: Reading Section 0x0002...OK
Xbe::Xbe: Reading Section 0x0003...OK
Xbe::Xbe: Reading Section 0x0004...OK
Xbe::Xbe: Reading Section 0x0005...OK
Xbe::Xbe: Reading Section 0x0006...OK
Xbe::Xbe: Reading Section 0x0007...OK
Xbe::Xbe: Reading Section 0x0008...OK
Xbe::Xbe: Reading Section 0x0009...OK
Xbe::Xbe: Reading Section 0x000A...OK
Xbe::Xbe: Reading Section 0x000B...OK
Xbe::Xbe: Reading Section 0x000C...OK
Xbe::Xbe: Reading Section 0x000D...OK
Xbe::Xbe: Reading Section 0x000E...OK
Xbe::Xbe: Reading Section 0x000F...OK
Xbe::Xbe: Reading Section 0x0010...OK
Xbe::Xbe: Reading Section 0x0011...OK
Xbe::Xbe: Reading Thread Local Storage...OK
WndMain: Iron Phoenix loaded.`

**Comment by fuhuan416** [comment]
And the Kernel debug console infoes:
`EmuMain (0x44C): Cxbx Version 0.8.1-Pre3
EmuMain (0x44C): Debug Console Allocated (DM_CONSOLE).
EmuMain (0x44C): Debug Trace Disabled.
Exe::Exe: Opening Exe file...OK
Exe::Exe: Reading DOS stub...Found, Ignoring...OK
Exe::Exe: Reading PE header...OK
Exe::Exe: Reading Optional Header...OK
Exe::Exe: Reading Section Headers...
Exe::Exe: Reading Section Header 0x0000...OK
Exe::Exe: Reading Section Header 0x0001...OK
Exe::Exe: Reading Section Header 0x0002...OK
Exe::Exe: Reading Section Header 0x0003...OK
Exe::Exe: Reading Section Header 0x0004...OK
Exe::Exe: Reading Section Header 0x0005...OK
Exe::Exe: Reading Section Header 0x0006...OK
Exe::Exe: Reading Section Header 0x0007...OK
Exe::Exe: Reading Section Header 0x0008...OK
Exe::Exe: Reading Section Header 0x0009...OK
Exe::Exe: Reading Section Header 0x000A...OK
Exe::Exe: Reading Section Header 0x000B...OK
Exe::Exe: Reading Section Header 0x000C...OK
Exe::Exe: Reading Section Header 0x000D...OK
Exe::Exe: Reading Section Header 0x000E...OK
Exe::Exe: Reading Section Header 0x000F...OK
Exe::Exe: Reading Section Header 0x0010...OK
Exe::Exe: Reading Section Header 0x0011...OK
Exe::Exe: Reading Section Header 0x0012...OK
Exe::Exe: Reading Section Header 0x0013...OK
Exe::Exe: Reading Sections...
Exe::Exe: Reading Section 0x0000...OK
Exe::Exe: Reading Section 0x0001...OK
Exe::Exe: Reading Section 0x0002...OK
Exe::Exe: Reading Section 0x0003...OK
Exe::Exe: Reading Section 0x0004...OK
Exe::Exe: Reading Section 0x0005...OK
Exe::Exe: Reading Section 0x0006...OK
Exe::Exe: Reading Section 0x0007...OK
Exe::Exe: Reading Section 0x0008...OK
Exe::Exe: Reading Section 0x0009...OK
Exe::Exe: Reading Section 0x000A...OK
Exe::Exe: Reading Section 0x000B...OK
Exe::Exe: Reading Section 0x000C...OK
Exe::Exe: Reading Section 0x000D...OK
Exe::Exe: Reading Section 0x000E...OK
Exe::Exe: Reading Section 0x000F...OK
Exe::Exe: Reading Section 0x0010...OK
Exe::Exe: Reading Section 0x0011...OK
Exe::Exe: Reading Section 0x0012...OK
Exe::Exe: Reading Section 0x0013...OK
Exe::Exe: C:\Users\FASTER\AppData\Local\Temp\default.exe was successfully opened.
CxbxDbg> EmuWarn (0xAA4): HalRegisterShutdownNotification not implemented!

EmuWarn (0xAA4): ExQueryNonVolatileSetting unknown ValueIndex (10)
EmuWarn (0xAA4): FscSetCacheSize is being ignored
EmuWarn (0xAA4): NtReadFile Failed! (0xC0000011)
EmuWarn (0xAA4): NtReadFile Failed! (0xC0000011)
EmuMain (0x1630): Recieved Fatal Message:

* IDirect3D8::CreateDevice failed (Invalid Call)`

**Comment by LukeUsher** [comment]
This is normal, most games don't work yet
At this point it would be more helpful to report which games do something,, rather than which don't boot at all
