### ISSUE TITLE
Title Screen - The Fairly OddParents: Breakin' da Rules

### ISSUE THREAD

**Issue by kwasior1** [LukeUsher/Cxbx-Reloaded#7]
![da rulz](https://cloud.githubusercontent.com/assets/3619041/19248622/8cca5a5a-8f31-11e6-9a92-e32aa9c395dd.png)

Fun fact - first game that I have ever booted up on xbox emulator.
Build from 2 weeks ago (and any before) crashes immediately.

Here is xbe file: 
[FOP.txt](https://github.com/LukeUsher/Cxbx-Reloaded/files/520267/FOP.txt)

**Comment by LukeUsher** [comment]
Great stuff, could you post this over at http://cxbx-reloaded.co.uk/compatibility please, The same for any future games that do something.

I need to update the readme to point there but didn't get around to it yet,

Thanks

**Comment by kwasior1** [comment]
Sure thing!

**Comment by JohnPaulHarold** [comment]
@LukeUsher one of these might help, https://help.github.com/articles/setting-guidelines-for-repository-contributors/ I thought there was a way of setting placeholder text for issues, but if there is, I can't find it right now.
